FROM @make:docker_base_image@

STOPSIGNAL SIGTERM

ENV semantic_wiki_installer_docker_image_setup_root=/var/local/workspaces/semantic-wiki-installer/setup

##

USER    root
WORKDIR "${semantic_wiki_installer_docker_image_setup_root}"

COPY ./ /opt/semantic-wiki-installer/
RUN  mv /opt/semantic-wiki-installer/test/* .
RUN  rm -rf /opt/semantic-wiki-installer/test

RUN  egrep -hv '^\s*#' conf/packages.needed.*.txt > packages.needed.filtered.txt

RUN  apt-get update && apt-get install -y apt-utils bash && \
	apt-get install -y $(cat packages.needed.filtered.txt) && \
	rm -rf /var/lib/apt/lists/* ;

##

USER    root
WORKDIR "${semantic_wiki_installer_docker_image_setup_root}"

ENTRYPOINT ["bash", "start.sh"]

##

