FROM @make:docker_base_image@

STOPSIGNAL SIGTERM

ENV provisioning_core_docker_image_setup_root=/var/local/workspaces/provisioning-core/setup

##

USER    root
WORKDIR "${provisioning_core_docker_image_setup_root}"

COPY ./ /opt/provisioning-core/
RUN  mv /opt/provisioning-core/test/* .
RUN  rm -rf /opt/provisioning-core/test

RUN ./provision.sh docker

##

USER    root
WORKDIR "${provisioning_core_docker_image_setup_root}"

ENTRYPOINT ["sh", "start.sh"]

##

